Repository NohYeongHun/zero-gifticon, pull requests merged in 2022-10, with the labels that each got.

#58 fix: giftBox 감사 메시지 아이디 가져오기
  backend/src/main/java/com/zerogift/backend/giftBox/dto/GiftBoxDetail.java
  backend/src/main/java/com/zerogift/backend/giftBox/dto/GiftBoxDto.java
  backend/src/main/java/com/zerogift/backend/giftBox/repository/GiftBoxRepositoryCustomImpl.java
  backend/src/main/java/com/zerogift/backend/giftMessage/repository/GiftMessageRepositoryCustomImpl.java
  backend/src/test/java/com/zerogift/backend/acceptance/giftBox/GiftBoxAcceptanceTest.java
  backend/src/test/java/com/zerogift/backend/documentaion/giftbox/FindByGiftBoxListStep.java
  backend/src/test/java/com/zerogift/backend/documentaion/giftbox/GetGiftBoxDetailStep.java
  backend/src/test/java/com/zerogift/backend/giftBox/service/GiftBoxServiceTest.java
Labels: ✨기능추가, 💯 테스트

#59 Develop feat/notice
  backend/src/main/java/com/zerogift/backend/giftMessage/service/GiftMessageService.java
  backend/src/main/java/com/zerogift/backend/likes/controller/LikesController.java
  backend/src/main/java/com/zerogift/backend/likes/service/LikesService.java
  backend/src/main/java/com/zerogift/backend/likes/service/LikesServiceImpl.java
  backend/src/main/java/com/zerogift/backend/notice/model/GiftMessageNoticeResponse.java
  backend/src/main/java/com/zerogift/backend/notice/model/GiftNoticeResponse.java
  backend/src/main/java/com/zerogift/backend/notice/model/NoticeTypeResponse.java
  backend/src/main/java/com/zerogift/backend/notice/service/NoticeService.java
  backend/src/main/java/com/zerogift/backend/notice/type/NoticeType.java
  backend/src/main/java/com/zerogift/backend/pay/service/PayService.java
  backend/src/main/java/com/zerogift/backend/review/model/ReviewResponse.java
  backend/src/main/java/com/zerogift/backend/review/service/ReviewServiceImpl.java
  backend/src/test/java/com/zerogift/backend/likes/service/LikesServiceImplTest.java
  backend/src/test/java/com/zerogift/backend/review/service/ReviewServiceTest.java
Labels: ⚙️ 리팩토링, 💯 테스트

#60 Develop feat/notice
  backend/src/main/java/com/zerogift/backend/common/exception/code/NoticeErrorCode.java
  backend/src/main/java/com/zerogift/backend/notice/controller/NoticeController.java
  backend/src/main/java/com/zerogift/backend/notice/repository/NoticeRepository.java
  backend/src/main/java/com/zerogift/backend/notice/service/NoticeService.java
Labels: ⚙️ 리팩토링

#61 addReview에서 gift를 list로 불러와서 사용
  backend/src/main/java/com/zerogift/backend/giftBox/repository/GiftBoxRepository.java
  backend/src/main/java/com/zerogift/backend/review/service/ReviewServiceImpl.java
Labels: 🚨 긴급수정

#64 fix: 일반 로그인 시, id 값이 없는 버그 수정
  module-api/src/main/java/com/zerogift/member/application/MemberLoginService.java
  module-api/src/main/java/com/zerogift/support/auth/userdetails/AdminInfo.java
  module-api/src/main/java/com/zerogift/support/auth/userdetails/MemberInfo.java
Labels: 🧑‍💻백엔드, 🐛 버그, 🚨 긴급수정

#74 [fix] 포인트 관련 수정 작업
  module-api/src/main/java/com/zerogift/global/error/code/GiftBoxErrorCode.java
  module-api/src/main/java/com/zerogift/product/application/ReviewServiceImpl.java
  module-api/src/main/resources/db/migration/V11__create_point_table.sql
  module-api/src/test/java/com/zerogift/application/ReviewServiceTest.java
  module-common/src/main/java/com/zerogift/pay/domain/PointHistory.java
  module-common/src/main/java/com/zerogift/pay/domain/PointType.java
  module-common/src/main/java/com/zerogift/pay/repository/PointHistoryRepository.java
  module-common/src/main/java/com/zerogift/product/repository/ReviewRepositoryCustom.java
  module-common/src/main/java/com/zerogift/product/repository/ReviewRepositoryCustomImpl.java
Labels: ⚙️ 리팩토링

#75 feat: docker 빌드 추가
  .github/workflows/deploy.yml
  README.md
  module-api/Dockerfile
Labels: 🏗 인프라
