Repository NohYeongHun/zero-gifticon, pull requests merged in 2022-09, with the labels that each got.

#1 OAuth Login 추가
  build.gradle
  src/main/java/com/example/demo/common/dto/Result.java
  src/main/java/com/example/demo/common/entity/RefreshToken.java
  src/main/java/com/example/demo/common/exception/OAuthException.java
  src/main/java/com/example/demo/common/exception/code/OAuthErrorCode.java
  src/main/java/com/example/demo/common/type/AuthType.java
  src/main/java/com/example/demo/config/JpaAuditConfig.java
  src/main/java/com/example/demo/config/RedisConfig.java
  src/main/java/com/example/demo/config/SecurityConfig.java
  src/main/java/com/example/demo/member/entity/Member.java
  src/main/java/com/example/demo/security/dto/AdminInfo.java
  src/main/java/com/example/demo/security/dto/GoogleOAuth2UserInfo.java
  src/main/java/com/example/demo/security/dto/KakaoOAuth2UserInfo.java
  src/main/java/com/example/demo/security/dto/LoginInfo.java
  src/main/java/com/example/demo/security/dto/MemberInfo.java
  src/main/java/com/example/demo/security/dto/OAuth2UserInfo.java
  src/main/java/com/example/demo/security/dto/OAuth2UserInfoFactory.java
  src/main/java/com/example/demo/security/dto/OAuthTokenResponse.java
  src/main/java/com/example/demo/security/dto/RefreshTokenInputDto.java
  src/main/java/com/example/demo/security/dto/TokenDto.java
  src/main/java/com/example/demo/security/repository/RefreshTokenRepository.java
  src/main/java/com/example/demo/security/service/OAuthService.java
  src/main/java/com/example/demo/security/service/TokenService.java
  src/main/java/com/example/demo/security/utils/JwtAccessDeniedHandler.java
  src/main/java/com/example/demo/security/utils/JwtAuthenticationFilter.java
  src/main/java/com/example/demo/security/utils/JwtAuthenticationProvider.java
  src/main/java/com/example/demo/security/utils/JwtAuthenticationToken.java
  src/main/java/com/example/demo/security/utils/JwtEntryPoint.java
  src/main/java/com/example/demo/security/utils/JwtInfo.java
  src/main/java/com/example/demo/security/web/AuthController.java
Labels: ✨기능추가, 🧑‍💻백엔드

#34 test 코드 수정작업
  backend/src/main/java/com/zerogift/backend/security/utils/JwtAuthenticationFilter.java
  backend/src/test/java/com/zerogift/backend/acceptance/giftBox/GiftBoxAcceptanceTest.java
  backend/src/test/java/com/zerogift/backend/acceptance/giftMessage/GiftMessageAcceptanceTest.java
  backend/src/test/java/com/zerogift/backend/acceptance/pay/PayHistoryAcceptanceTest.java
  backend/src/test/java/com/zerogift/backend/step/PayHistoryStep.java
  backend/src/test/java/com/zerogift/backend/step/ProductStep.java
Labels: 🐛 버그, 💯 테스트

#38 긴급수정: swagger 에서 JWT 적용이 안됨
  backend/src/main/java/com/zerogift/backend/config/SwaggerConfig.java
  backend/src/main/java/com/zerogift/backend/config/authorization/AuthenticationPrincipalArgumentResolver.java
  backend/src/main/java/com/zerogift/backend/giftBox/controller/GiftBoxController.java
  backend/src/main/java/com/zerogift/backend/giftBox/repository/GiftBoxRepositoryCustom.java
  backend/src/main/java/com/zerogift/backend/giftBox/repository/GiftBoxRepositoryCustomImpl.java
  backend/src/main/java/com/zerogift/backend/giftBox/service/GiftBoxService.java
  backend/src/main/java/com/zerogift/backend/giftMessage/repository/GiftMessageRepositoryCustomImpl.java
  backend/src/main/java/com/zerogift/backend/security/service/GeneralService.java
  backend/src/main/java/com/zerogift/backend/security/utils/JwtAuthenticationProvider.java
  backend/src/test/java/com/zerogift/backend/giftBox/service/GiftBoxServiceTest.java
Labels: 🚨 긴급수정

#37 Develop feat/review
  backend/src/main/java/com/zerogift/backend/common/exception/code/ReviewErrorCode.java
  backend/src/main/java/com/zerogift/backend/common/exception/review/ReviewException.java
  backend/src/main/java/com/zerogift/backend/giftBox/repository/GiftBoxRepository.java
  backend/src/main/java/com/zerogift/backend/member/model/MemberReviewResponse.java
  backend/src/main/java/com/zerogift/backend/product/dto/ProductReviewResponse.java
  backend/src/main/java/com/zerogift/backend/review/controller/ReviewController.java
  backend/src/main/java/com/zerogift/backend/review/entity/Review.java
  backend/src/main/java/com/zerogift/backend/review/model/ReviewInput.java
  backend/src/main/java/com/zerogift/backend/review/model/ReviewResponse.java
  backend/src/main/java/com/zerogift/backend/review/repository/ReviewRepository.java
  backend/src/main/java/com/zerogift/backend/review/service/ReviewService.java
  backend/src/main/java/com/zerogift/backend/review/service/ReviewServiceImpl.java
  backend/src/test/java/com/zerogift/backend/review/service/ReviewServiceTest.java
Labels: ✨기능추가, 🧑‍💻백엔드, 💯 테스트

#40 결제시 상품 카운트 다운 기능 추가
  backend/build.gradle
  backend/src/main/java/com/zerogift/backend/common/exception/code/PayErrorCode.java
  backend/src/main/java/com/zerogift/backend/common/exception/pay/NotEnoughProductCountException.java
  backend/src/main/java/com/zerogift/backend/common/exception/pay/PayRedissonClientException.java
  backend/src/main/java/com/zerogift/backend/config/AopConfig.java
  backend/src/main/java/com/zerogift/backend/giftBox/controller/GiftBoxController.java
  backend/src/main/java/com/zerogift/backend/giftBox/dto/GiftBoxDetail.java
  backend/src/main/java/com/zerogift/backend/giftBox/dto/GiftBoxDto.java
  backend/src/main/java/com/zerogift/backend/giftBox/repository/GiftBoxRepositoryCustomImpl.java
  backend/src/main/java/com/zerogift/backend/giftMessage/controller/GiftMessageController.java
  backend/src/main/java/com/zerogift/backend/pay/aop/PayLock.java
  backend/src/main/java/com/zerogift/backend/pay/aop/PayLockAop.java
  backend/src/main/java/com/zerogift/backend/pay/service/LockService.java
  backend/src/main/java/com/zerogift/backend/pay/service/PayService.java
  backend/src/main/java/com/zerogift/backend/pay/type/LockStatus.java
  backend/src/main/java/com/zerogift/backend/product/entity/Product.java
  backend/src/main/java/springfox/documentation/spring/web/plugins/WebMvcRequestHandlerProvider.java
  backend/src/test/java/com/zerogift/backend/acceptance/giftBox/GiftBoxAcceptanceTest.java
  backend/src/test/java/com/zerogift/backend/acceptance/giftMessage/GiftMessageAcceptanceTest.java
  backend/src/test/java/com/zerogift/backend/pay/service/PayServiceTest.java
  backend/src/test/java/com/zerogift/backend/step/GiftBoxStep.java
  backend/src/test/java/com/zerogift/backend/utils/DataMakeUtils.java
Labels: ✨기능추가, 🧑‍💻백엔드, 🐛 버그, 🧹 설정, 💯 테스트

#42 선물함 응답값 추가 ( 선물 보낸 사람, 상품 아이디, 메시지 여부, 리뷰 여부)
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/zerogift/backend/giftBox/dto/GiftBoxDto.java
  backend/src/main/java/com/zerogift/backend/giftBox/entity/GiftBox.java
  backend/src/main/java/com/zerogift/backend/giftBox/repository/GiftBoxRepositoryCustomImpl.java
  backend/src/main/java/com/zerogift/backend/pay/service/LockService.java
  backend/src/main/java/com/zerogift/backend/review/service/ReviewServiceImpl.java
  backend/src/test/java/com/zerogift/backend/acceptance/giftBox/GiftBoxAcceptanceTest.java
  backend/src/test/java/com/zerogift/backend/documentaion/giftbox/FindByGiftBoxListStep.java
  backend/src/test/java/com/zerogift/backend/giftBox/service/GiftBoxServiceTest.java
Labels: ✨기능추가, 🐛 버그, 💯 테스트

#43 회원 결제 정보 검색 기능
  backend/src/main/java/com/zerogift/backend/member/dto/MemberSearchDetail.java
  backend/src/main/java/com/zerogift/backend/member/repository/MemberSearchRepository.java
  backend/src/main/java/com/zerogift/backend/member/service/MemberSearchService.java
  backend/src/main/java/com/zerogift/backend/member/web/MemberSearchController.java
  backend/src/test/java/com/zerogift/backend/member/service/MemberSearchServiceTest.java
Labels: ✨기능추가

#44 rest docs 불필요한 파라미터 때문에 빌드 에러 발생으로 긴급 수정
  backend/src/docs/asciidoc/index.adoc
Labels: 🚨 긴급수정

#45 DB 마이그레이션을 위한 flyway 추가
  backend/build.gradle
  backend/src/main/resources/db/migration/V0__init.sql
  backend/src/main/resources/db/migration/V1__create_product_table.sql
  backend/src/main/resources/db/migration/V2__create_giftBox_table.sql
  backend/src/main/resources/db/migration/V3__create_like_table.sql
  backend/src/main/resources/db/migration/V4__create_view_table.sql
  backend/src/main/resources/db/migration/V5__create_pay_table.sql
  backend/src/main/resources/db/migration/V6__create_email_table.sql
  backend/src/main/resources/db/migration/V7__create_review_table.sql
  backend/src/main/resources/db/migration/V8__create_notice_table.sql
Labels: 🧑‍💻백엔드, 🧹 설정, 🏗 인프라

#46 감사메시지, 결제 restdocs 작성
  backend/src/docs/asciidoc/giftBox.adoc
  backend/src/docs/asciidoc/giftMessage.adoc
  backend/src/docs/asciidoc/pay.adoc
  backend/src/test/java/com/zerogift/backend/documentaion/GiftMessageDocumentation.java
  backend/src/test/java/com/zerogift/backend/documentaion/PayDocumentation.java
  backend/src/test/java/com/zerogift/backend/documentaion/giftMessage/GetGiftMessageStep.java
  backend/src/test/java/com/zerogift/backend/documentaion/pay/PayStep.java
Labels: 🧑‍💻백엔드, 💯 테스트

#48 Develop feat/review
  backend/src/main/java/com/zerogift/backend/review/controller/ReviewController.java
Labels: 🚨 긴급수정

#50 fix: 받는사람 보내는 사람 변경
  backend/src/main/java/com/zerogift/backend/pay/service/PayService.java
Labels: 🚨 긴급수정

#51 Product 엔티티 liked 컬럼 삭제 등
  backend/src/main/java/com/zerogift/backend/common/exception/code/ProductErrorCode.java
  backend/src/main/java/com/zerogift/backend/product/controller/ProductController.java
  backend/src/main/java/com/zerogift/backend/product/dto/MyProductDto.java
  backend/src/main/java/com/zerogift/backend/product/entity/Product.java
  backend/src/main/java/com/zerogift/backend/product/service/ProductService.java
Labels: ✨기능추가, ⚙️ 리팩토링

#52 테스트 코드 추가 등
  backend/src/main/java/com/zerogift/backend/common/exception/code/ProductErrorCode.java
  backend/src/main/java/com/zerogift/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/zerogift/backend/product/service/ProductService.java
  backend/src/test/java/com/zerogift/backend/product/service/ProductServiceTest.java
Labels: 🐛 버그, 💯 테스트
